# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-15 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pseudo',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='summary',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Null', max_length=30),
            preserve_default=False,
        ),
    ]
